spring.application.name=user-management

spring.datasource.url=jdbc:postgresql://localhost:5432/user_management
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=kbrsphere-secret-key-user-management-very-long-secret-key

spring.jpa.hibernate.ddl-auto=update