spring.application.name=email-service
server.port=8085

# Mailtrap SMTP Configuration
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=YOUR_MAILTRAP_USERNAME
spring.mail.password=YOUR_MAILTRAP_PASSWORD

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Optional (for debugging)
spring.mail.properties.mail.debug=true

# Custom
email.from=no-reply@kbrsphere.com
